# -*- coding: utf-8 -*-
"""M-Hアルゴリズム.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1g3Tyn89O8-RviiytXmrZlTtZd_FdI0EX
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import beta
import pandas as pd
# %matplotlib inline

plt.style.use("ggplot")
np.random.seed(123)

a, b = 1.5, 2.0
x = np.linspace(beta.ppf(0.001,a,b), beta.ppf(0.999, a,b), 100)
plt.plot(x, beta.pdf(x, a, b))

theta = 0.8
NMCS = 20000
epsilon = 0.5
theta_mcs = [theta]
for i in range(NMCS):
    theta_new = theta + epsilon * np.random.randn()
    if beta.pdf(theta_new, a, b) > beta.pdf(theta, a, b):
        theta = theta_new
    else:
        r = beta.pdf(theta_new, a, b) / beta.pdf(theta, a, b)
        if np.random.rand() < r:
            theta = theta_new
    theta_mcs.append(theta)
df = pd.DataFrame(theta_mcs)

df.head()

plt.plot(df[0])
plt.xlabel("MCS")
plt.ylabel("$\Theta$")

plt.hist(df[0][1000:], normed=True, bins=40)
x = np.linspace(beta.ppf(0.001,a,b), beta.ppf(0.999, a,b), 100)
plt.plot(x, beta.pdf(x, a, b))

