# -*- coding: utf-8 -*-
"""MAP推定.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1BvcevtiGwY7LtbNF58lPJADILNdUVncb
"""

# Commented out IPython magic to ensure Python compatibility.
import numpy as np
from scipy import optimize
import matplotlib.pyplot as plt
from scipy import stats
import pandas as pd
# %matplotlib inline

plt.style.use("ggplot")

df = pd.read_excel("./data/MAP_sample.xlsx", index_col="id")

df.head()

plt.hist(df["value"])

def likelihood(mu, *args):
    li = -np.log10(stats.norm.pdf(mu, loc=args))
    return(np.sum(li))

optimize.minimize(likelihood, 1, args=df["value"])

